version: '2'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PMA_ARBITRARY: '1'
      PMA_HOST: db
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - '8888:80'

  redis:
    container_name: greenbee_redis
    restart: unless-stopped
    image: redis:6-alpine
    command: --requirepass ${REDIS_PASSWORD}
    expose:
      - '${REDIS_PORT}'
    env_file:
      - .env
    networks:
      - app-network

  backend:
    build:
      context: ./backend/
    volumes:
      - ./backend/:/usr/app
      - backend_node_modules:/usr/app/node_modules
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      REDIS_HOST: redis
      CHOKIDAR_USEPOLLING: 'true' # create-ui-app <= 5.x
      WATCHPACK_POLLING: 'true' # create-ui-app >= 5.x
      FAST_REFRESH: 'true'
      DB_HOST: '${DB_HOST}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_NAME: '${DB_NAME}'
      SESSION_SECRET: '${SESSION_SECRET}'
      NODE_ENV: 'development'
      WDS_SOCKET_HOST: '127.0.0.1'   
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/
    command: npm start
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend/:/usr/app
      - frontend_node_modules:/usr/app/node_modules
    links:
      - backend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  backend_node_modules:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge
